"use client";

import { useMemo, useState } from "react";

import { ImagePreview } from "@/components/image-preview";
import { StatusBadge } from "@/components/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useNormalizedBaseAssets } from "@/hooks/use-normalized-base-assets";

export default function NormalizedBasesPage() {
  const { data: assets, isLoading } = useNormalizedBaseAssets();
  const [search, setSearch] = useState("");

  const filteredAssets = useMemo(() => {
    const term = search.trim().toLowerCase();
    return (assets || []).filter((asset) => {
      return !term || [asset.vehicle_key, asset.make, asset.model, asset.trim, asset.base_asset_id, asset.filename]
        .some((value) => String(value || "").toLowerCase().includes(term));
    });
  }, [assets, search]);

  if (isLoading) {
    return <div className="text-slate-400">Loading normalized base PNG assets...</div>;
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Normalized Bases</h1>
        <p className="text-slate-400">PNG assets generated by ai-background-remover and cached for recolor reuse</p>
      </div>

      <div className="rounded-3xl border border-slate-800/70 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 p-4 shadow-[0_20px_60px_-30px_rgba(15,23,42,0.85)]">
        <Input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search by vehicle key, make, model, trim, base asset id or filename"
          className="h-10 border-slate-700 bg-slate-950/80 text-slate-100"
        />
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {filteredAssets.map((asset) => (
          <Card key={asset.id} className="border-slate-800 bg-slate-900">
            <CardHeader>
              <CardTitle className="text-white">{asset.make} {asset.model} {asset.trim}</CardTitle>
              <div className="flex items-center gap-2">
                <StatusBadge status={asset.status} />
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <ImagePreview
                src={asset.normalized_image_url}
                alt={`${asset.make} ${asset.model}`}
                width={300}
                height={200}
              />
              <div className="space-y-2 text-sm text-slate-300">
                <p><span className="font-medium">Vehicle key:</span> {asset.vehicle_key || "-"}</p>
                <p><span className="font-medium">Base asset:</span> {asset.base_asset_id}</p>
                <p><span className="font-medium">Filename:</span> {asset.filename}</p>
                <p><span className="font-medium">Size:</span> {(asset.file_size_bytes / 1024).toFixed(1)} KB</p>
              </div>
              {asset.base_image_url && (
                <a
                  href={asset.base_image_url}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex rounded-lg border border-slate-700 px-3 py-2 text-xs text-slate-200 transition hover:border-slate-500 hover:bg-slate-800/70"
                >
                  Open original base
                </a>
              )}
            </CardContent>
          </Card>
        ))}

        {filteredAssets.length === 0 && (
          <div className="col-span-full py-10 text-center text-slate-400">
            No normalized base PNG assets found
          </div>
        )}
      </div>
    </div>
  );
}
